[package]
name = "elasticgrid_ae"
version = "0.9.0"
edition = "2024"
rust-version = "1.85"
license = "Proprietary"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[features]
default = ["native-plane"]
native-plane = []

[dependencies]
after-effects = "=0.4.0"
serde = { version = "=1.0.229", features = ["derive"] }

[build-dependencies]
pipl = "=0.1.1"
cc = "=1.5.1"

[dev-dependencies]
bincode = { version = "=2.0.1", features = ["serde"] }
