#include "NativeInstaller.h"
#include "Payload.h"
#include <shlobj.h>
#include <sddl.h>
#include <aclapi.h>
#include <tlhelp32.h>
#include <bcrypt.h>
#include <algorithm>
#include <array>
#include <fstream>
#include <cwctype>
#include <regex>
#include <sstream>
#include <stdexcept>

namespace fs=std::filesystem;
namespace fstr::installer {
namespace {
constexpr const wchar_t* target=L"FSTR Stretch.aex";
struct Handle { HANDLE h; explicit Handle(HANDLE v):h(v){} ~Handle(){if(h && h!=INVALID_HANDLE_VALUE)CloseHandle(h);} Handle(const Handle&)=delete; };
struct Local { void* p=nullptr; ~Local(){if(p)LocalFree(p);} };
void need(bool condition,const char* reason){if(!condition)throw std::runtime_error(reason);}
std::wstring wide(const char* p){std::wstring out;for(;*p;++p)out.push_back(static_cast<wchar_t>(static_cast<unsigned char>(*p)));return out;}
bool pathPresent(const fs::path& p){auto a=GetFileAttributesW(p.c_str());if(a!=INVALID_FILE_ATTRIBUTES)return true;auto e=GetLastError();need(e==ERROR_FILE_NOT_FOUND || e==ERROR_PATH_NOT_FOUND,"Cannot inspect a path.");return false;}
Handle open(const fs::path& p,DWORD access=GENERIC_READ,DWORD sharing=FILE_SHARE_READ|FILE_SHARE_DELETE){
    HANDLE h=CreateFileW(p.c_str(),access,sharing,nullptr,OPEN_EXISTING,FILE_FLAG_OPEN_REPARSE_POINT|FILE_FLAG_BACKUP_SEMANTICS,nullptr);need(h!=INVALID_HANDLE_VALUE,"Cannot safely open a file or folder.");
    FILE_ATTRIBUTE_TAG_INFO info{};if(!GetFileInformationByHandleEx(h,FileAttributeTagInfo,&info,sizeof(info)) || (info.FileAttributes&FILE_ATTRIBUTE_REPARSE_POINT)){CloseHandle(h);throw std::runtime_error("Reparse points are not supported. Nothing replaced.");}return Handle(h);
}
void noLinks(const fs::path& p){fs::path current=p.root_path();for(const auto& part:p.relative_path()){current/=part;if(!pathPresent(current))break;auto h=open(current,FILE_READ_ATTRIBUTES,FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE);}}
std::vector<unsigned char> currentSid(){Handle token(nullptr);need(OpenProcessToken(GetCurrentProcess(),TOKEN_QUERY,&token.h)!=0,"Cannot inspect process identity.");DWORD size=0;GetTokenInformation(token.h,TokenUser,nullptr,0,&size);std::vector<unsigned char> bytes(size);need(size && GetTokenInformation(token.h,TokenUser,bytes.data(),size,&size),"Cannot inspect process identity.");PSID sid=reinterpret_cast<TOKEN_USER*>(bytes.data())->User.Sid;std::vector<unsigned char> out(GetLengthSid(sid));need(CopySid(static_cast<DWORD>(out.size()),out.data(),sid),"Cannot copy process identity.");return out;}
bool trusted(PSID sid){std::array<unsigned char,SECURITY_MAX_SID_SIZE> admin{},system{};DWORD a=static_cast<DWORD>(admin.size()),s=static_cast<DWORD>(system.size());need(CreateWellKnownSid(WinBuiltinAdministratorsSid,nullptr,admin.data(),&a) && CreateWellKnownSid(WinLocalSystemSid,nullptr,system.data(),&s),"Cannot inspect native principals.");auto user=currentSid();DWORD n=0, domainSize=0;SID_NAME_USE use{};LookupAccountNameW(nullptr,L"NT SERVICE\\TrustedInstaller",nullptr,&n,nullptr,&domainSize,&use);std::vector<unsigned char> service(n);std::vector<wchar_t> domain(domainSize);bool serviceKnown=n && LookupAccountNameW(nullptr,L"NT SERVICE\\TrustedInstaller",service.data(),&n,domain.data(),&domainSize,&use);return EqualSid(sid,admin.data()) || EqualSid(sid,system.data()) || EqualSid(sid,user.data()) || (serviceKnown && EqualSid(sid,service.data()));}
std::string security(const fs::path& p,bool enforce=true,HANDLE handle=INVALID_HANDLE_VALUE){
    PSECURITY_DESCRIPTOR descriptor=nullptr;PSID owner=nullptr;PACL dacl=nullptr;
    DWORD result=handle==INVALID_HANDLE_VALUE?GetNamedSecurityInfoW(const_cast<wchar_t*>(p.c_str()),SE_FILE_OBJECT,OWNER_SECURITY_INFORMATION|GROUP_SECURITY_INFORMATION|DACL_SECURITY_INFORMATION,&owner,nullptr,&dacl,nullptr,&descriptor):GetSecurityInfo(handle,SE_FILE_OBJECT,OWNER_SECURITY_INFORMATION|GROUP_SECURITY_INFORMATION|DACL_SECURITY_INFORMATION,&owner,nullptr,&dacl,nullptr,&descriptor);Local saved{descriptor};need(result==ERROR_SUCCESS && descriptor && owner && dacl,"Cannot verify file security.");
    if(enforce){need(trusted(owner),"Folder or file belongs to another user; it is preserved.");
        constexpr DWORD mutation=FILE_WRITE_DATA|FILE_APPEND_DATA|FILE_WRITE_EA|FILE_WRITE_ATTRIBUTES|DELETE|WRITE_DAC|WRITE_OWNER|GENERIC_WRITE|GENERIC_ALL;
        for(DWORD i=0;i<dacl->AceCount;++i){void* ace=nullptr;need(GetAce(dacl,i,&ace),"Cannot read access rules.");auto header=static_cast<ACE_HEADER*>(ace);if(header->AceFlags&INHERIT_ONLY_ACE)continue;if(header->AceType==ACCESS_DENIED_ACE_TYPE)continue;need(header->AceType==ACCESS_ALLOWED_ACE_TYPE,"Unsupported access rule; files preserved.");auto allowed=static_cast<ACCESS_ALLOWED_ACE*>(ace);if(allowed->Mask&mutation)need(trusted(&allowed->SidStart),"Unsafe write access. Files preserved.");}}
    LPWSTR text=nullptr;need(ConvertSecurityDescriptorToStringSecurityDescriptorW(descriptor,SDDL_REVISION_1,OWNER_SECURITY_INFORMATION|GROUP_SECURITY_INFORMATION|DACL_SECURITY_INFORMATION,&text,nullptr),"Cannot record file security.");Local string{text};std::string out;for(const wchar_t* c=text;*c;++c){need(*c<128,"Unexpected security record.");out.push_back(static_cast<char>(*c));}return out;
}
fs::path known(REFKNOWNFOLDERID id);
void secure(const fs::path& p){
    noLinks(p);if(!pathPresent(p)){secure(p.parent_path());Local descriptor;need(ConvertStringSecurityDescriptorToSecurityDescriptorW(L"D:P(A;OICI;FA;;;SY)(A;OICI;FA;;;BA)(A;OICI;GRGX;;;BU)",SDDL_REVISION_1,&descriptor.p,nullptr),"Cannot prepare protected folder.");SECURITY_ATTRIBUTES attributes{sizeof(SECURITY_ATTRIBUTES),descriptor.p,FALSE};need(CreateDirectoryW(p.c_str(),&attributes),"Cannot create protected folder.");}
    need((GetFileAttributesW(p.c_str())&FILE_ATTRIBUTE_DIRECTORY)!=0,"Folder required.");security(p,p!=known(FOLDERID_ProgramData));
}
std::string sha(const std::vector<unsigned char>& data){
    BCRYPT_ALG_HANDLE alg=nullptr;need(BCryptOpenAlgorithmProvider(&alg,BCRYPT_SHA256_ALGORITHM,nullptr,0)>=0,"SHA256 unavailable.");std::array<unsigned char,32> hash{};auto status=BCryptHash(alg,nullptr,0,const_cast<PUCHAR>(data.data()),static_cast<ULONG>(data.size()),hash.data(),static_cast<ULONG>(hash.size()));BCryptCloseAlgorithmProvider(alg,0);need(status>=0,"SHA256 failed.");std::string out;const char* hex="0123456789abcdef";for(auto b:hash){out+=hex[b>>4];out+=hex[b&15];}return out;
}
std::vector<unsigned char> read(const fs::path& p){
    noLinks(p);auto h=open(p);BY_HANDLE_FILE_INFORMATION a{},b{};need(GetFileInformationByHandle(h.h,&a) && !(a.dwFileAttributes&FILE_ATTRIBUTE_DIRECTORY) && a.nNumberOfLinks==1 && !a.nFileSizeHigh && a.nFileSizeLow<=32*1024*1024,"Unsupported file layout.");std::vector<unsigned char> bytes(a.nFileSizeLow);DWORD used=0;need(bytes.empty() || (ReadFile(h.h,bytes.data(),static_cast<DWORD>(bytes.size()),&used,nullptr) && used==bytes.size()),"Cannot read file.");need(GetFileInformationByHandle(h.h,&b) && a.nFileIndexHigh==b.nFileIndexHigh && a.nFileIndexLow==b.nFileIndexLow && a.nFileSizeLow==b.nFileSizeLow && CompareFileTime(&a.ftLastWriteTime,&b.ftLastWriteTime)==0,"File changed during inspection.");return bytes;
}
struct Snapshot {
    DWORD volume=0,high=0,low=0,attributes=0,size=0;FILETIME created{},modified{};std::string hash,acl;
    bool operator==(const Snapshot& b) const{return volume==b.volume && high==b.high && low==b.low && attributes==b.attributes && size==b.size && CompareFileTime(&created,&b.created)==0 && CompareFileTime(&modified,&b.modified)==0 && hash==b.hash && acl==b.acl;}
};
Snapshot snapshot(const fs::path& p){auto bytes=read(p);auto h=open(p);BY_HANDLE_FILE_INFORMATION i{};need(GetFileInformationByHandle(h.h,&i) && i.nNumberOfLinks==1,"Cannot record file identity.");WIN32_FIND_STREAM_DATA stream{};HANDLE streams=FindFirstStreamW(p.c_str(),FindStreamInfoStandard,&stream,0);need(streams!=INVALID_HANDLE_VALUE,"Cannot inspect file streams.");bool only=std::wstring(stream.cStreamName)==L"::$DATA" && !FindNextStreamW(streams,&stream) && GetLastError()==ERROR_HANDLE_EOF;FindClose(streams);need(only && !(i.dwFileAttributes&(FILE_ATTRIBUTE_ENCRYPTED|FILE_ATTRIBUTE_COMPRESSED|FILE_ATTRIBUTE_READONLY)),"Alternate streams, encrypted/compressed or read-only files are not supported.");return {i.dwVolumeSerialNumber,i.nFileIndexHigh,i.nFileIndexLow,i.dwFileAttributes,i.nFileSizeLow,i.ftCreationTime,i.ftLastWriteTime,sha(bytes),security(p)};}
std::string identity(const fs::path& p){auto bytes=read(p);std::string text(bytes.begin(),bytes.end());need(text.starts_with("MZ") && text.find("com.elasticgrid.fx.warp")!=text.npos,"Unknown installed plugin preserved.");std::regex regex("ElasticGridBuildID=(EGFX-[0-9a-f]{24})");std::sregex_iterator begin(text.begin(),text.end(),regex),end;need(begin!=end,"Missing installed build identity.");std::string found=(*begin)[1].str();for(auto i=begin;i!=end;++i)need((*i)[1].str()==found,"Multiple build identities found.");return found;}
void scan(const fs::path& p,std::vector<fs::path>& found,unsigned depth=0){noLinks(p);if(!pathPresent(p))return;need(depth<=12,"Plugin scan depth exceeded.");for(const auto& item:fs::directory_iterator(p)){noLinks(item.path());if(item.is_directory()){auto name=item.path().filename().wstring();if(name.starts_with(L'(') && name.ends_with(L')'))continue;scan(item.path(),found,depth+1);}else if(item.path().extension()==L".aex"){auto bytes=read(item.path());std::string text(bytes.begin(),bytes.end());auto name=item.path().filename().wstring();std::transform(name.begin(),name.end(),name.begin(),[](wchar_t c){return static_cast<wchar_t>(towlower(c));});if(name==L"fstr stretch.aex" || name.find(L"elasticgrid")!=name.npos || text.find("com.elasticgrid.fx.warp")!=text.npos)found.push_back(item.path());}}}
void environment(const InstallEnvironment& e,bool present){e.checkHosts();std::vector<fs::path> found;for(const auto& p:e.scanRoots)scan(p,found);std::sort(found.begin(),found.end());found.erase(std::unique(found.begin(),found.end()),found.end());need(found.size()==(present?1u:0u) && (!present || found.front()==e.active/target),"Another or unknown copy was found. Remove the conflict first; nothing replaced.");noLinks(e.active);noLinks(e.backups);security(e.active);security(e.backups);}
void write(const fs::path& p,const void* bytes,std::size_t size){noLinks(p);Handle h(CreateFileW(p.c_str(),GENERIC_READ|GENERIC_WRITE,0,nullptr,CREATE_NEW,FILE_ATTRIBUTE_NORMAL,nullptr));need(h.h!=INVALID_HANDLE_VALUE,"Cannot create exclusive transaction file.");DWORD done=0;need(size<=32*1024*1024 && (size==0 || (WriteFile(h.h,bytes,static_cast<DWORD>(size),&done,nullptr) && done==size)) && FlushFileBuffers(h.h),"Cannot durably write transaction file.");security(p,true,h.h);}
std::string encode(const Snapshot& s){std::ostringstream out;out<<s.volume<<' '<<s.high<<' '<<s.low<<' '<<s.attributes<<' '<<s.size<<' '<<s.created.dwHighDateTime<<' '<<s.created.dwLowDateTime<<' '<<s.modified.dwHighDateTime<<' '<<s.modified.dwLowDateTime<<'\n'<<s.hash<<'\n'<<s.acl<<'\n';return out.str();}
Snapshot decode(std::istream& in){Snapshot s;need(static_cast<bool>(in>>s.volume>>s.high>>s.low>>s.attributes>>s.size>>s.created.dwHighDateTime>>s.created.dwLowDateTime>>s.modified.dwHighDateTime>>s.modified.dwLowDateTime),"Invalid recovery snapshot.");need(in.get()=='\n' && static_cast<bool>(std::getline(in,s.hash)) && static_cast<bool>(std::getline(in,s.acl)) && std::regex_match(s.hash,std::regex("[0-9a-f]{64}")) && s.acl.size()<=4096 && s.size<=32*1024*1024,"Invalid recovery snapshot.");return s;}
struct Receipt {bool oldPresent;Snapshot old,candidate;};
Receipt receipt(const fs::path& tx){auto b=read(tx/L"prepared");need(b.size()<16384,"Invalid recovery receipt.");std::istringstream in(std::string(b.begin(),b.end()));std::string magic,present;need(static_cast<bool>(std::getline(in,magic)) && magic=="FSTR-WINDOWS-1" && static_cast<bool>(std::getline(in,present)) && (present=="0" || present=="1"),"Invalid recovery receipt.");Receipt r{present=="1",{},decode(in)};if(r.oldPresent)r.old=decode(in);need(in.peek()==EOF,"Trailing recovery data.");return r;}
void mark(const fs::path& tx,const wchar_t* name){write(tx/name,nullptr,0);}
Snapshot published(const fs::path& tx){auto b=read(tx/L"published");std::istringstream in(std::string(b.begin(),b.end()));auto s=decode(in);need(in.peek()==EOF,"Invalid publication record.");return s;}
fs::path known(REFKNOWNFOLDERID id){PWSTR s=nullptr;need(SHGetKnownFolderPath(id,0,nullptr,&s)==S_OK,"Cannot resolve native system folder.");fs::path out(s);CoTaskMemFree(s);need(out.is_absolute() && out.root_name().wstring().size()==2,"Local native folder required.");noLinks(out);return out;}
void hosts(){Handle snapshotHandle(CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS,0));need(snapshotHandle.h!=INVALID_HANDLE_VALUE,"Cannot inspect Adobe processes.");PROCESSENTRY32W entry{};entry.dwSize=sizeof(entry);need(Process32FirstW(snapshotHandle.h,&entry),"Process scan incomplete.");do{std::wstring name(entry.szExeFile);std::transform(name.begin(),name.end(),name.begin(),[](wchar_t c){return static_cast<wchar_t>(towlower(c));});for(const auto* n:{L"afterfx.exe",L"aerender.exe",L"adobe media encoder.exe",L"adobe premiere pro.exe",L"dynamiclinkmanager.exe"})need(name!=n,"Close After Effects and other Adobe render applications, then try again.");}while(Process32NextW(snapshotHandle.h,&entry));need(GetLastError()==ERROR_NO_MORE_FILES,"Process scan incomplete.");}
}
bool elevated(){Handle token(nullptr);if(!OpenProcessToken(GetCurrentProcess(),TOKEN_QUERY,&token.h))return false;TOKEN_ELEVATION e{};DWORD size=0;return GetTokenInformation(token.h,TokenElevation,&e,sizeof(e),&size) && e.TokenIsElevated;}
InstallEnvironment systemEnvironment(){auto programs=known(FOLDERID_ProgramFiles);auto data=known(FOLDERID_ProgramData);InstallEnvironment e{programs/L"Adobe/Common/Plug-ins/7.0/MediaCore/FSTR FX",data/L"FSTR FX/Backups",{},hosts};e.scanRoots.push_back(e.active.parent_path());if(pathPresent(programs/L"Adobe"))for(const auto& p:fs::directory_iterator(programs/L"Adobe"))if(p.is_directory() && p.path().filename().wstring().starts_with(L"Adobe After Effects"))e.scanRoots.push_back(p.path()/L"Support Files/Plug-ins");auto profiles=programs.root_path()/L"Users";if(pathPresent(profiles))for(const auto& p:fs::directory_iterator(profiles))if(p.is_directory() && !p.is_symlink())e.scanRoots.push_back(p.path()/L"AppData/Roaming/Adobe/Common/Plug-ins/7.0/MediaCore");return e;}
std::wstring runNative(const InstallEnvironment& e,bool restore){
    e.checkHosts();secure(e.active);secure(e.backups);auto rootA=open(e.active,FILE_READ_ATTRIBUTES),rootB=open(e.backups,FILE_READ_ATTRIBUTES);BY_HANDLE_FILE_INFORMATION a{},b{};need(GetFileInformationByHandle(rootA.h,&a) && GetFileInformationByHandle(rootB.h,&b) && a.dwVolumeSerialNumber==b.dwVolumeSerialNumber,"Active and backup folders must be on the same volume. No copy/delete fallback.");
    auto lockPath=e.active/L".fstr-install-lock-v1";noLinks(lockPath);Handle lock(CreateFileW(lockPath.c_str(),GENERIC_READ|GENERIC_WRITE,0,nullptr,OPEN_ALWAYS,FILE_FLAG_OPEN_REPARSE_POINT,nullptr));need(lock.h!=INVALID_HANDLE_VALUE,"Another installer is running.");BY_HANDLE_FILE_INFORMATION lockInfo{};need(GetFileInformationByHandle(lock.h,&lockInfo) && !(lockInfo.dwFileAttributes&(FILE_ATTRIBUTE_DIRECTORY|FILE_ATTRIBUTE_REPARSE_POINT)) && lockInfo.nNumberOfLinks==1 && !lockInfo.nFileSizeHigh && !lockInfo.nFileSizeLow,"Unsafe installer lock.");security(lockPath,true,lock.h);
    bool present=pathPresent(e.active/target);environment(e,present);if(present)identity(e.active/target);
    std::vector<fs::path> records;for(const auto& p:fs::directory_iterator(e.backups)){noLinks(p.path());need(p.is_directory(),"Unknown backup entry preserved.");security(p.path());records.push_back(p.path());}std::sort(records.rbegin(),records.rend());fs::path pending;for(const auto& p:records)if(!pathPresent(p/L"installed") && !pathPresent(p/L"restored")){need(pending.empty(),"Multiple incomplete transactions need inspection.");pending=p;}
    if(restore){fs::path tx=pending;if(tx.empty())for(const auto& p:records)if(pathPresent(p/L"installed") && !pathPresent(p/L"restored")){tx=p;break;}need(!tx.empty(),"No previous installation is available.");auto r=receipt(tx);
        if(!r.oldPresent){need(present && snapshot(e.active/target)==published(tx),"Fresh installation needs manual recovery; all files retained.");if(!pending.empty())mark(tx,L"installed");return L"No previous version exists. Fresh installation verified; no files removed.";}
        if(!pathPresent(tx/L"published")){need(present && snapshot(e.active/target)==r.old && pathPresent(tx/L"staged.aex") && snapshot(tx/L"staged.aex")==r.candidate && !pathPresent(tx/L"previous.aex"),"Interrupted replacement needs manual recovery. Both versions retained.");mark(tx,L"restored");return L"Replacement did not start. Previous version is unchanged; you can try Install again.";}
        need(present && snapshot(e.active/target)==published(tx) && snapshot(tx/L"previous.aex")==r.old && !pathPresent(tx/L"current.aex"),"Restore refused: current or previous files changed.");environment(e,true);
        need(ReplaceFileW((e.active/target).c_str(),(tx/L"previous.aex").c_str(),(tx/L"current.aex").c_str(),0,nullptr,nullptr),"Restore incomplete. Both versions retained; manual recovery required.");
        need(snapshot(e.active/target).hash==r.old.hash && snapshot(tx/L"current.aex").hash==r.candidate.hash,"Restore verification failed. Both versions retained.");auto post=snapshot(e.active/target);auto encoded=encode(post);write(tx/L"restored-payload",encoded.data(),encoded.size());mark(tx,L"restored");return L"Previous version restored. Both versions are retained in Backups.";
    }
    need(pending.empty(),"An interrupted installation was found. Choose Restore before another installation.");need(payload::count==1,"Invalid Windows payload layout.");const auto& f=payload::files[0];std::vector<unsigned char> embedded(f.bytes,f.bytes+f.size);need(sha(embedded)==f.sha256,"Embedded payload checksum failed.");if(present && identity(e.active/target)==payload::buildId){need(snapshot(e.active/target).hash==f.sha256,"Installed identity has different bytes; preserved.");return L"This version is already installed.";}
    GUID uuid{};need(CoCreateGuid(&uuid)==S_OK,"Cannot allocate transaction.");wchar_t guid[40];need(StringFromGUID2(uuid,guid,40)>0,"Cannot format transaction.");FILETIME time{};GetSystemTimeAsFileTime(&time);auto ticks=(static_cast<unsigned long long>(time.dwHighDateTime)<<32)|time.dwLowDateTime;auto tx=e.backups/(std::to_wstring(ticks)+L"-"+guid);secure(tx);write(tx/L"staged.aex",f.bytes,f.size);auto candidate=snapshot(tx/L"staged.aex");need(candidate.hash==f.sha256 && identity(tx/L"staged.aex")==payload::buildId,"Wrong staged candidate.");Receipt r{present,present?snapshot(e.active/target):Snapshot{},candidate};auto text=std::string("FSTR-WINDOWS-1\n")+(present?"1\n":"0\n")+encode(r.candidate)+(present?encode(r.old):"");write(tx/L"prepared",text.data(),text.size());environment(e,present);need(snapshot(tx/L"staged.aex")==candidate && (!present || snapshot(e.active/target)==r.old),"Payload changed before publication; retained for recovery.");
    bool ok=present?ReplaceFileW((e.active/target).c_str(),(tx/L"staged.aex").c_str(),(tx/L"previous.aex").c_str(),0,nullptr,nullptr)!=0:MoveFileExW((tx/L"staged.aex").c_str(),(e.active/target).c_str(),MOVEFILE_WRITE_THROUGH)!=0;
    need(ok,"Publication incomplete. Transaction retained; choose Restore for inspection. Partial ReplaceFile failures may require manual recovery.");environment(e,true);auto post=snapshot(e.active/target);need(post.hash==f.sha256 && post.volume==candidate.volume && post.high==candidate.high && post.low==candidate.low && (!present || snapshot(tx/L"previous.aex")==r.old),"Post-install verification failed; files retained.");text=encode(post);write(tx/L"published",text.data(),text.size());mark(tx,L"installed");return present?L"Installed. Previous version saved in Backups.":L"Installed. No previous version was present.";
}
}
